<pre>Name       :    Chaitanya Machhindra Nawale

Roll no    :    BECOB215

Subject    :    ML

Assignment :    KNN Classification
</pre>


Problem Statement : Assignment on KNN Classification
In the following diagram let blue circles indicate positive examples and orange squares indicate negative examples.
We want to use k-NN algorithm for classifying the points. If k=3, find the class of the point (6,6).
Extend the same example for Distance-Weighted k-NN and Locally weighted Averaging.


In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score

In [2]:
dataset = pd.DataFrame({'x':[2,4,4,4,6,6],
                        'y':[4,2,4,6,2,4],
                        'class':['negative','negative','positive','negative','positive','negative']})
dataset

x  y     class
0  2  4  negative
1  4  2  negative
2  4  4  positive
3  4  6  negative
4  6  2  positive
5  6  4  negative

In [3]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [4]:
x

array([[2, 4],
       [4, 2],
       [4, 4],
       [4, 6],
       [6, 2],
       [6, 4]])

In [5]:
y

array(['negative', 'negative', 'positive', 'negative', 'positive',
       'negative'], dtype=object)

# General KNN

In [6]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x,y)
knn_y_pred = knn.predict(x) 
knn_y_pred

array(['negative', 'positive', 'negative', 'negative', 'negative',
       'positive'], dtype=object)

In [7]:
print(str(accuracy_score(y,knn_y_pred)))
print(str(confusion_matrix(y,knn_y_pred)))
print(str(f1_score(y,knn_y_pred,average=None)))

0.3333333333333333
[[2 2]
 [2 0]]
[0.5 0. ]


# Distance weighted KNN

In [8]:
w_knn = KNeighborsClassifier(n_neighbors =3, weights = 'distance')
w_knn.fit(x,y)
w_knn_y_pred = w_knn.predict(x) 
w_knn_y_pred

array(['negative', 'negative', 'positive', 'negative', 'positive',
       'negative'], dtype=object)

In [9]:
print(str(accuracy_score(y,w_knn_y_pred)))
print(str(confusion_matrix(y,w_knn_y_pred)))
print(str(f1_score(y,w_knn_y_pred,average=None)))

1.0
[[4 0]
 [0 2]]
[1. 1.]


# Local weighted averaging

In [10]:
from sklearn.neighbors import NearestCentroid
LWA = NearestCentroid()
LWA.fit(x,y)
print(LWA.centroids_)
LWA_y_pred = LWA.predict(x)
LWA_y_pred

[[4. 4.]
 [5. 3.]]


array(['negative', 'positive', 'negative', 'negative', 'positive',
       'positive'], dtype=object)

In [11]:
print(str(accuracy_score(y,LWA_y_pred)))
print(str(confusion_matrix(y,LWA_y_pred)))
print(str(f1_score(y,LWA_y_pred,average=None)))

0.5
[[2 2]
 [1 1]]
[0.57142857 0.4       ]


In [12]:
print('Class of the point (6,6) : ')
print('by General K-NN : ',''.join(knn.predict([np.array([6,6])])))
print('by Weighted K-NN : ',''.join(w_knn.predict([np.array([6,6])])))
print('by Locally Weighted Averaging : ',''.join(LWA.predict([np.array([6,6])])))

Class of the point (6,6) : 
by General K-NN :  negative
by Weighted K-NN :  negative
by Locally Weighted Averaging :  negative
